# Generated by Django 6.0.6 on 2026-06-07 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('mediocampista', 'Mediocampista'), ('delantero', 'Delantero')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EquipoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.equipo')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_como_sede', to='core.sede')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_participantes', to='core.temporada')),
            ],
            options={
                'unique_together': {('temporada', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='PlantillaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.PositiveIntegerField()),
                ('posicion_secundaria', models.CharField(blank=True, choices=[('portero', 'Portero'), ('defensa', 'Defensa'), ('mediocampista', 'Mediocampista'), ('delantero', 'Delantero')], max_length=20, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('equipo_temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla', to='core.equipotemporada')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_equipos', to='core.jugador')),
            ],
            options={
                'ordering': ['dorsal'],
                'unique_together': {('equipo_temporada', 'jugador')},
            },
        ),
    ]
