# Generated by Django 6.0.6 on 2026-06-07 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_jugador_equipo_jugador_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='federacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.federacion'),
        ),
    ]
