# Generated by Django 6.0.6 on 2026-06-07 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipo_federacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='federacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.federacion'),
        ),
    ]
